apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  POSTGRES_DB: "dGVzdF9kYg=="
  POSTGRES_USER: "cG9zdGdyZXM="
  POSTGRES_PASSWORD: "MTIz"

