apiVersion: apps/v1
name: test-app-server
namespace: test-app
labels:
  name: test-app-server
  component: backend
  instance: test-app-server

# Deployment configuration
replicas: 1
revisionHistoryLimit: 3
image:
  # docker image name
  repository: huma-app
  tag: latest
  pullPolicy: Never
strategy:
  type: RollingUpdate
  maxUnavailable: 50%
  maxSurge: 1
livenessProbe:
  httpGet:
    path: /health
    port: 3500
  initialDelaySeconds: 15
  periodSeconds: 360
readinessProbe:
  httpGet:
    path: /health
    port: 3500
  periodSeconds: 360
resources:
  requests: # minimum resources required
    memory: "64Mi"
    cpu: "150m"
  limits: # maximum resources allowed
    memory: "64Mi"
    cpu: "200m"

# Service configuration
service:
  type: ClusterIP
  port: 3500
  targetPort: 3500

# Ingress (traefik) configuration
ingress:
  enabled: true
  # setup in /var/lib/rancher/k3s/server/manifests
  entryPoint: backend
  match: PathPrefix(`/`)
  kind: Rule

# Horizontal Pod Autoscaler configuration
autoscaling:
  enabled: false
  kind: Deployment
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50

configmap:
  CLIENT_IP: "http://192.168.85.128" # change k3s node IP as needed
  CLIENT_PORT: "32000" # NodePort of client service
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://alloy.monitoring.svc.cluster.local:4318"
  OTEL_SERVICE_NAME: "otel-go-service"
  OTEL_EXPORTER_OTLP_PROTOCOL: "http/protobuf"
  OTEL_RESOURCE_ATTRIBUTES: "deployment.environment=production"

secret: # secrets must be base64 encoded
  DB_USER: "cG9zdGdyZXM="
  DB_PASSWORD: "MTIz"