apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "label.component" . | nindent 4 }}
data:
  CLIENT_IP: "http://192.168.85.128" # change k3s node IP as needed
  CLIENT_PORT: "32000" # NodePort of client service
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://alloy.monitoring.svc.cluster.local:4318"
  OTEL_SERVICE_NAME: "otel-go-service"
  OTEL_EXPORTER_OTLP_PROTOCOL: "http/protobuf"
  OTEL_RESOURCE_ATTRIBUTES: "deployment.environment=production"
    

