apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "label.component" . | nindent 4 }}
type: Opaque
data:
  DB_USER: "cG9zdGdyZXM="
  DB_PASSWORD: "MTIz"